### ISSUE TITLE
Release v4.2.0.23-beta won't open

### ISSUE THREAD

**Issue by ezonius** [Artentus/ModMyFactory2#22]
Release v4.1.2.22-beta works fine though.

The only thing in log was: 
`2020-12-19 13:08:40.245 +01:00 [INF] Operating system: Microsoft Windows 10.0.19042
2020-12-19 13:08:40.283 +01:00 [INF] Runtime: .NET 5.0.0`

**Comment by Artentus** [comment]
Can confirm, looks like the new runtime has broken the automated build process.  

The universal release works though, you can use that one instead until I can figure this out.

**Comment by hurr1k4ne** [comment]
confirm, 4.2.0.23 (win build) does not open in Win10 

```
[10:08:47 INF] Operating system: Microsoft Windows 10.0.19041
[10:08:47 INF] Runtime: .NET 5.0.0
Unhandled exception. System.TypeInitializationException: The type initializer for 'ModMyFactoryGUI.VersionStatistics' threw an exception.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at ModMyFactoryGUI.VersionStatistics..cctor() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\VersionStatistics.cs:line 105
   --- End of inner exception stack trace ---
   at ModMyFactoryGUI.Program.InitLogger(OptionsBase options) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 139
   at ModMyFactoryGUI.Program.StartAppAsync(String[] args, RunOptions options) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 362
   at ModMyFactoryGUI.Program.Main(String[] args) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 570
   at ModMyFactoryGUI.Program.<Main>(String[] args)
```

**Comment by Artentus** [comment]
Thank you, this log is actually really helpful. I didn't get any log myself but this pinpoints it.
