### ISSUE TITLE
Found a bug by accident

### ISSUE THREAD

**Issue by BlueWeabo** [Artentus/ModMyFactory2#36]
Unhandled exception. System.ArgumentException: Mod has incorrect Factorio version.
   at ModMyFactory.Mods.ModManager.Add(Mod mod)
   at ModMyFactoryGUI.ManagerExtensions.LoadModsAsync(Manager manager, LocationManager locations) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\ManagerExtensions.cs:line 93
   at ModMyFactoryGUI.LocationManager.InitializeAsync() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\LocationManager.cs:line 304
   at ModMyFactoryGUI.GlobalSingletonFactory.CreateManagerAsync(SettingManager settings) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\GlobalSingletonFactory.cs:line 32
   at ModMyFactoryGUI.Program.InitProgramAsync(OptionsBase options) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 213
   at ModMyFactoryGUI.Program.StartAppAsync(String[] args, RunOptions options) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 374
   at ModMyFactoryGUI.Program.Main(String[] args) in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 581
   at ModMyFactoryGUI.Program.<Main>(String[] args)
   i got this error when i was working on a mod and had missed a number in the factorio version. I was trying to figure out how to find out why it stopped working so suddenly as i updated to the latest version. I needed to run the program in command promt to find out the issue. Hope you could if possible make it so you catch this error. Will put todays log file after i found out the issue.
[log_20210212.txt](https://github.com/Artentus/ModMyFactory2/files/5971603/log_20210212.txt)

**Comment by Artentus** [comment]
Actually this is sort if intended because if a mod with the incorrect Factorio version is in the mod folder of that particular version something went wrong. You're right MMF probably shouldn't just crash but I think silently ignoring it could lead to confusion. On the other hand I don't really want to spam the user with dialogs on start if I can avoid it. What do you think is the most helpful solution?

**Comment by BlueWeabo** [comment]
I am not sure as i haven't done almost any programming, but you could maybe export a window saying "wrong mod factorio version in folder <name of folder>." and maybe make it a choice between deleting the files or look into the folder of the wrong mod.

**Comment by Ethrel** [comment]
Personally, in this case, I'd probably present a dialogue that offered the option to move the mod to the right folder, or ignore it. If you're already doing the version check, that should mean you'd be able to figure out where it belongs. I would avoid any silent move operations, because I know I, personally, don't like it when I've specifically done something and programs "clean up" after me. That's how I lose files.

That said, adding an option to 'ignore' the problem in that same dialogue is fine too. Somehow mark the mod as possibly problematic, show it in the UI with a little symbol and tooltip or something, and then wash your hands of the problem. If they specifically tell the automated systems to ignore it, assume they know what they're doing. Just make sure that the "fix it" option is default and the one that draws the eye first so people don't click ignore without thinking about it.

Possibly, add a button that does the same task as "fix it" in the UI if the mod is marked as problematic, so that accidental "ignores" can be rectified with a minimum of hassle.
